apiVersion: v1               
kind: Pod                    
metadata:
  name: nginx-hello
  namespace: namespace-yan
spec:
  containers:
  - image: nginx   
    name: nginx    
    ports:
    - containerPort: 8080
      protocol: TCP